# docker-compose -f docker-compose.prod.yml pull
# docker-compose -f docker-compose.prod.yml up

services:
  backend:
    image: ilmeloil/notas-backend:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ilmeloil/notas-frontend:latest
    ports:
      - "8081:8081"
      - "19006:19006"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    restart: unless-stopped